insert into concepto (id, descripcion_concepto, puntos_requeridos) values (1, 'Monitored well-modulated core', 19);
insert into concepto (id, descripcion_concepto, puntos_requeridos) values (2, 'Reduced explicit interface', 14);
insert into concepto (id, descripcion_concepto, puntos_requeridos) values (3, 'Profound actuating core', 4);
insert into concepto (id, descripcion_concepto, puntos_requeridos) values (4, 'Organized asynchronous alliance', 12);
insert into concepto (id, descripcion_concepto, puntos_requeridos) values (5, 'Face to face real-time hierarchy', 6);
insert into concepto (id, descripcion_concepto, puntos_requeridos) values (6, 'Reduced client-driven software', 19);
insert into concepto (id, descripcion_concepto, puntos_requeridos) values (7, 'Stand-alone optimal support', 5);
insert into concepto (id, descripcion_concepto, puntos_requeridos) values (8, 'Digitized multimedia installation', 20);
insert into concepto (id, descripcion_concepto, puntos_requeridos) values (9, 'Universal intangible forecast', 11);
insert into concepto (id, descripcion_concepto, puntos_requeridos) values (10, 'Proactive 24 hour emulation', 6);
insert into concepto (id, descripcion_concepto, puntos_requeridos) values (11, 'Progressive static approach', 7);
insert into concepto (id, descripcion_concepto, puntos_requeridos) values (12, 'Multi-tiered leading edge functionalities', 15);
insert into concepto (id, descripcion_concepto, puntos_requeridos) values (13, 'Reverse-engineered neutral success', 5);
insert into concepto (id, descripcion_concepto, puntos_requeridos) values (14, 'Focused 4th generation service-desk', 9);
insert into concepto (id, descripcion_concepto, puntos_requeridos) values (15, 'Integrated foreground intranet', 19);
insert into concepto (id, descripcion_concepto, puntos_requeridos) values (16, 'Multi-lateral zero defect solution', 2);
insert into concepto (id, descripcion_concepto, puntos_requeridos) values (17, 'Open-source transitional initiative', 1);
insert into concepto (id, descripcion_concepto, puntos_requeridos) values (18, 'Future-proofed fault-tolerant archive', 11);
insert into concepto (id, descripcion_concepto, puntos_requeridos) values (19, 'Grass-roots attitude-oriented definition', 15);
insert into concepto (id, descripcion_concepto, puntos_requeridos) values (20, 'Balanced dynamic core', 17);
